name: Kernel Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            bc bison build-essential ccache curl flex gcc git \
            libelf-dev libssl-dev lld llvm clang \
            python3 python3-pip rsync zip unzip \
            dwarves pahole device-tree-compiler \
            libncurses-dev busybox cpio libselinux* \
            libssl-dev openssl 

      - name: Build kernel
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload boot.img
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: boot-M145F
          path: ./boot.img
          if-no-files-found: error
          retention-days: 7
